//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMAPlaylistWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistSong
    {
        public int ID { get; set; }
        public Nullable<int> Playlist { get; set; }
        public Nullable<int> Song { get; set; }
    
        public virtual Playlist Playlist1 { get; set; }
        public virtual Song Song1 { get; set; }
    }
}
