//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMAPlaylistWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongArtist
    {
        public int ID { get; set; }
        public Nullable<int> Song { get; set; }
        public Nullable<int> Artist { get; set; }
    
        public virtual Artist Artist1 { get; set; }
        public virtual Song Song1 { get; set; }
    }
}
